INSERT INTO powersets(powersetName) VALUES
("Arachnos Soldier"),
("Archery"),
("Assault Rifle"),
("Atomic Manipulation"),
("Bane Spider Soldier"),
("Bane Spider Training"),
("Battle Axe"),
("Beam Rifle"),
("Beast Mastery"),
("Bio Armor"),
("Broad Sword"),
("Claws"),
("Cold Domination"),
("Crab Spider Soldier"),
("Crab Spider Training"),
("Dark Armor"),
("Dark Assault"),
("Dark Blast"),
("Dark Mastery"),
("Dark Melee"),
("Dark Miasma"),
("Darkness Affinity"),
("Darkness Control"),
("Darkness Manipulation"),
("Demon Summoning"),
("Devices"),
("Dual Blades"),
("Dual Pistols"),
("Earth Assault"),
("Earth Control"),
("Electric Armor"),
("Electric Control"),
("Electrical Blast"),
("Electrical Melee"),
("Electricity Assault"),
("Electricity Manipulation"),
("Electricity Mastery"),
("Empathy"),
("Energy Assault"),
("Energy Aura"),
("Energy Blast"),
("Energy Manipulation"),
("Energy Melee"),
("Fiery Assault"),
("Fiery Aura"),
("Fiery Melee"),
("Fire Blast"),
("Fire Control"),
("Fire Manipulation"),
("Fire Mastery"),
("Force Field"),
("Fortunata Teamwork"),
("Fortunata Training"),
("Gravity Control"),
("Ice Armor"),
("Ice Blast"),
("Ice Control"),
("Ice Manipulation"),
("Ice Mastery"),
("Ice Melee"),
("Icy Assault"),
("Illusion Control"),
("Invulnerability"),
("Katana"),
("Kinetic Melee"),
("Kinetics"),
("Leviathan Mastery"),
("Luminous Aura"),
("Luminous Blast"),
("Mace Mastery"),
("Martial Arts"),
("Martial Assault"),
("Martial Combat"),
("Mental Manipulation"),
("Mercenaries"),
("Mind Control"),
("Mu Mastery"),
("Nature Affinity"),
("Necromancy"),
("Night Widow Training"),
("Ninja Blade"),
("Ninja Tool Mastery"),
("Ninja Training"),
("Ninjas"),
("Ninjitsu"),
("Pain Domination"),
("Plant Control"),
("Plant Manipulation"),
("Poison"),
("Psionic Assault"),
("Psionic Mastery"),
("Psionic Melee"),
("Psychic Blast"),
("Radiation Armor"),
("Radiation Blast"),
("Radiation Emission"),
("Radiation Melee"),
("Radioactive Assault"),
("Regeneration"),
("Robotics"),
("Savage Assault"),
("Savage Melee"),
("Shield Defense"),
("Sonic Attack"),
("Sonic Attacks"),
("Sonic Resonance"),
("Soul Mastery"),
("Spines"),
("Staff Fighting"),
("Stone Armor"),
("Stone Melee"),
("Storm Summoning"),
("Street Justice"),
("Super Reflexes"),
("Super Strength"),
("Tactical Arrow"),
("Teamwork"),
("Temporal Manipulation"),
("Thermal Radiation"),
("Thorny Assault"),
("Thugs"),
("Time Manipulation"),
("Titan Weapons"),
("Training and Gadgets"),
("Traps"),
("Trick Arrow"),
("Umbral Aura"),
("Umbral Blast"),
("War Mace"),
("Water Blast"),
("Widow Teamwork"),
("Widow Training"),
("Willpower");
