INSERT INTO powers(powerName) VALUES
("Ablating Strike"),
("Ablative Carapace"),
("Absorb Pain"),
("Absorption"),
("Abyssal Empowerment"),
("Abyssal Gaze"),
("Accelerate Metabolism"),
("Acid Arrow"),
("Acid Mortar"),
("Active Defense"),
("Adaptation"),
("Adrenalin Boost"),
("Against All Odds"),
("Agile"),
("Agility"),
("Aging Touch"),
("Aim"),
("Aimed Shot"),
("Alkaloid"),
("Alpha Barrier"),
("Amplify"),
("Anguishing Cry"),
("Animate Stone"),
("Antidote"),
("Antumbral Beam"),
("Aqua Bolt"),
("Arc of Destruction"),
("Arctic Air"),
("Arctic Breath"),
("Arctic Fog"),
("Arm Lash"),
("Assassin's Blade"),
("Assassin's Blades"),
("Assassin's Blaze"),
("Assassin's Blow"),
("Assassin's Claw"),
("Assassin's Corruption"),
("Assassin's Eclipse"),
("Assassin's Frenzy"),
("Assassin's Ice Sword"),
("Assassin's Impaler"),
("Assassin's Psi Blade"),
("Assassin's Shock"),
("Assassin's Slash"),
("Assassin's Staff"),
("Assassin's Strike"),
("Assault Bot"),
("Athletic Regulation"),
("Atom Smasher"),
("Atomic Blast"),
("Aura of Confusion"),
("Ball Lightning"),
("Bane Spider Armor Upgrade"),
("Barb Swipe"),
("Barrage"),
("Bash"),
("Battle Agility"),
("Battle Drones"),
("Bayonet"),
("Beanbag"),
("Beheader"),
("Benumb"),
("Beta Decay"),
("Bitter Freeze Ray"),
("Bitter Ice Blast"),
("Black Dwarf"),
("Black Hole"),
("Blackstar"),
("Blaze"),
("Blazing Arrow"),
("Blazing Aura"),
("Blazing Blast"),
("Blazing Bolt"),
("Blind"),
("Blinding Feint"),
("Blinding Powder"),
("Blizzard"),
("Block of Ice"),
("Blood Craze"),
("Blood Thirst"),
("Bo Ryaku"),
("Body Blow"),
("Boggle"),
("Bone Smasher"),
("Bonfire"),
("Boost Range"),
("Boundless Energy"),
("Breath of Fire"),
("Bright Nova"),
("Brimstone Armor"),
("Buckshot"),
("Build Momentum"),
("Build Up"),
("Bullet Rain"),
("Burn"),
("Burst"),
("Burst of Speed"),
("Call Bruiser"),
("Call Enforcer"),
("Call Genin"),
("Call Hawk"),
("Call Jounin"),
("Call Ravens"),
("Call Reinforcements"),
("Call Swarm"),
("Call Thugs"),
("Calling the Wolf"),
("Caltrops"),
("Carrion Creepers"),
("Cauterize"),
("Cauterizing Aura"),
("Cauterizing Blaze"),
("Chain Fences"),
("Chain Induction"),
("Channelgun"),
("Char"),
("Charged Armor"),
("Charged Bolts"),
("Charged Brawl"),
("Charged Shield"),
("Charged Shot"),
("Chemical Ammunition"),
("Chilblain"),
("Chilling Embrace"),
("Chilling Ray"),
("Choking Cloud"),
("Choking Powder"),
("Chop"),
("Chrono Shift"),
("Chronos"),
("Cinders"),
("Clarity"),
("Clear Mind"),
("Cleave"),
("Cloak of Darkness"),
("Cloak of Fear"),
("Cloaking Device"),
("Clobber"),
("Cobra Strike"),
("Combat Readiness"),
("Combat Training: Defensive"),
("Combat Training: Offensive"),
("Combustion"),
("Commando"),
("Concentrated Strike"),
("Concentration"),
("Conductive Aura"),
("Conductive Shield"),
("Conduit of Pain"),
("Confront"),
("Confuse"),
("Conserve Energy"),
("Consume"),
("Contaminated Strike"),
("Corrosive Enzymes"),
("Corruption"),
("Cosmic Burst"),
("Crab Spider Armor Upgrade"),
("Crack Whip"),
("Crane Kick"),
("Cremate"),
("Crippling Axe Kick"),
("Crowd Control"),
("Crush"),
("Crushing Blow"),
("Crushing Field"),
("Crushing Uppercut"),
("Cryo Ammunition"),
("Crystal Armor"),
("Cutting Beam"),
("Dampening Field"),
("Danger Sense"),
("Dark Blast"),
("Dark Consumption"),
("Dark Detonation"),
("Dark Embrace"),
("Dark Empowerment"),
("Dark Extraction"),
("Dark Grasp"),
("Dark Nova"),
("Dark Obliteration"),
("Dark Pit"),
("Dark Regeneration"),
("Dark Servant"),
("Darkest Night"),
("Dart Burst"),
("Dawn Strike"),
("Death Shroud"),
("Deceive"),
("Defensive Adaptation"),
("Defensive Sweep"),
("Deflection"),
("Deflection Shield"),
("Dehydrate"),
("Detention Field"),
("Detonator"),
("Devastating Blow"),
("Dimension Shift"),
("Disembowel"),
("Disintegrate"),
("Dismiss Pain"),
("Disorienting Shot"),
("Dispersion Bubble"),
("Disrupt"),
("Disruption Arrow"),
("Disruption Field"),
("Distortion Field"),
("Divine Avalanche"),
("DNA Siphon"),
("Dodge"),
("Dominate"),
("Dragon's Roar"),
("Dragon's Tail"),
("Drain Psyche"),
("Dreadful Wail"),
("Dual Wield"),
("Dull Pain"),
("Durability"),
("Eagle Eye"),
("Eagles Claw"),
("Earthquake"),
("Earth's Embrace"),
("Ebon Eye"),
("Eclipse"),
("Efficient Adaptation"),
("Electric Fence"),
("Electric Shackles"),
("Electrified Net Arrow"),
("Electrifying Fences"),
("Electron Haze"),
("Electron Shackles"),
("Elixir of Life"),
("Elude"),
("EM Pulse"),
("Embrace of Fire"),
("EMP Arrow"),
("Empty Clips"),
("Enchant Demon"),
("Enchant Undead"),
("End of Time"),
("Enduring"),
("Energize"),
("Energy Absorption"),
("Energy Cloak"),
("Energy Drain"),
("Energy Protection"),
("Energy Punch"),
("Energy Torrent"),
("Energy Transfer"),
("Enervating Field"),
("Enforced Morale"),
("Engulfing Darkness"),
("Entangle"),
("Entangling Arrow"),
("Entangling Aura"),
("Entropic Aura"),
("Entropy Shield"),
("Envenom"),
("Envenomed Blades"),
("Environmental Adaptation"),
("Environmental Modification"),
("Environmental Resistance"),
("Equip Mercenary"),
("Equip Robot"),
("Equip Thugs"),
("ESD Arrow"),
("Essence Boost"),
("Essence Drain"),
("Evasion"),
("Eviscerate"),
("Evolving Armor"),
("Executioner's Shot"),
("Explosive Arrow"),
("Explosive Blast"),
("Explosive Shuriken"),
("Eye of the Storm"),
("Fade"),
("Fallout"),
("Fallout Shelter"),
("Farsight"),
("Fast Healing"),
("Fault"),
("Fearsome Stare"),
("Feral Charge"),
("Field Operative"),
("Fiery Embrace"),
("Fire Ball"),
("Fire Blast"),
("Fire Breath"),
("Fire Cages"),
("Fire Imps"),
("Fire Shield"),
("Fire Sword"),
("Fire Sword Circle"),
("Fissure"),
("Fistful of Arrows"),
("Flamethrower"),
("Flares"),
("Flash"),
("Flash Arrow"),
("Flash Freeze"),
("Flashfire"),
("Flashing Steel"),
("Fling Thorns"),
("Fly Trap"),
("Focus"),
("Focus Chi"),
("Focused Accuracy"),
("Focused Burst"),
("Focused Fighting"),
("Focused Power Bolt"),
("Focused Senses"),
("Follow Through"),
("Follow Up"),
("Foot Stomp"),
("Force Bolt"),
("Force Bubble"),
("Force Field Generator"),
("Force of Thunder"),
("Foresight"),
("Forge"),
("Form of the Body"),
("Form of the Mind"),
("Form of the Soul"),
("Fortification"),
("Fortify Pack"),
("Fortitude"),
("Fossilize"),
("Frag Grenade"),
("Freeze Ray"),
("Freezing Rain"),
("Freezing Touch"),
("Frenzy"),
("Frigid Protection"),
("Frigid Shield"),
("Frost"),
("Frost Breath"),
("Frost Protection"),
("Frostbite"),
("Frostwork"),
("Frozen Armor"),
("Frozen Aura"),
("Frozen Fists"),
("Fulcrum Shift"),
("Full Auto"),
("Fusion"),
("Future Pain"),
("Gale"),
("Gambler's Cut"),
("Gamma Boost"),
("Gang War"),
("Gash"),
("Gather Shadows"),
("Genetic Contamination"),
("Genetic Corruption"),
("Genomic Evolution"),
("Geyser"),
("Glacial Armor"),
("Glacial Shield"),
("Glacier"),
("Gleaming Blast"),
("Gleaming Bolt"),
("Glinting Eye"),
("Gloom"),
("Glowing Touch"),
("Glue Arrow"),
("Golden Dragonfly"),
("Granite Armor"),
("Grant Cover"),
("Grave Knight"),
("Gravimetric Snare"),
("Gravitic Emanation"),
("Gravity Distortion"),
("Gravity Distortion Field"),
("Gravity Shield"),
("Gravity Well"),
("Greater Fire Sword"),
("Greater Ice Sword"),
("Greater Psi Blade"),
("Gremlins"),
("Ground Zero"),
("Grounded"),
("Group Energy Flight"),
("Group Invisibility"),
("Guarded Spin"),
("Gun Drone"),
("Gymnastics"),
("Hack"),
("Hail of Bullets"),
("Hand Clap"),
("Hardened Carapace"),
("Haunt"),
("Havoc Punch"),
("Haymaker"),
("Head Splitter"),
("Heal Other"),
("Healing Aura"),
("Healing Flames"),
("Heart of Darkness"),
("Heat Exhaustion"),
("Heat Loss"),
("Heavy Blow"),
("Heavy Burst"),
("Heavy Mallet"),
("Heightened Senses"),
("Hell on Earth"),
("Hemorrhage"),
("Hibernate"),
("Hide"),
("High Pain Tolerance"),
("Hoarfrost"),
("Hot Feet"),
("Howl"),
("Howling Twilight"),
("Hurl"),
("Hurl Boulder"),
("Hurricane"),
("Hydro Blast"),
("Ice Arrow"),
("Ice Blast"),
("Ice Bolt"),
("Ice Patch"),
("Ice Shield"),
("Ice Slash"),
("Ice Slick"),
("Ice Storm"),
("Ice Sword"),
("Ice Sword Circle"),
("Icicles"),
("Icy Bastion"),
("Ignite"),
("Immobilizing Dart"),
("Impale"),
("Incandescence"),
("Incandescent Strike"),
("Incendiary Ammunition"),
("Incinerate"),
("Incinerator"),
("Increase Density"),
("Indomitable Will"),
("Inertial Reduction"),
("Inexhaustible"),
("Inferno"),
("Infrigidate"),
("Initial Strike"),
("Inky Aspect"),
("Inner Light"),
("Inner Will"),
("Innocuous Strikes"),
("Instant Healing"),
("Instant Regeneration"),
("Insulation Shield"),
("Integration"),
("Invincibility"),
("Invincible"),
("Ionize"),
("Irradiate"),
("Irradiated Ground"),
("Jab"),
("Jack Frost"),
("Jacobs Ladder"),
("Jawbreaker"),
("Jolting Chain"),
("Kemuridama"),
("Ki Push"),
("Kinetic Dampening"),
("Kinetic Shield"),
("Knockout Blow"),
("Kuji In Zen"),
("Kuji-In Retsu"),
("Kuji-In Rin"),
("Kuji-In Sha"),
("Kuji-In Toh"),
("Lancer Shot"),
("Lash"),
("Levitate"),
("Lich"),
("Life Drain"),
("Lifegiving Spores"),
("Lift"),
("Light Form"),
("Lightning Bolt"),
("Lightning Clap"),
("Lightning Field"),
("Lightning Reflexes"),
("Lightning Rod"),
("Lightning Storm"),
("Lingering Radiation"),
("Link Minds"),
("Liquefy"),
("Living Shadows"),
("Longfang"),
("Lucky"),
("Luminous Detonation"),
("Lunge"),
("M30 Grenade"),
("Mace Beam"),
("Mace Beam Blast"),
("Mace Beam Volley"),
("Maiming Slash"),
("Mask Presence"),
("Mass Confusion"),
("Mass Hypnosis"),
("Mass Levitate"),
("Master Brawler"),
("Masterful Throw"),
("Melt Armor"),
("Meltdown"),
("Mental Blast"),
("Mental Strike"),
("Mental Training"),
("Mercurial Blow"),
("Mesmerize"),
("Metabolic Acceleration"),
("Midnight Grasp"),
("Mind Link"),
("Mind Over Body"),
("Mind Probe"),
("Minerals"),
("Moisture Absorption"),
("Molten Embrace"),
("Moment of Glory"),
("Moon Beam"),
("Moonbeam"),
("Mud Pots"),
("Murky Cloud"),
("Mutation"),
("Nebulous Form"),
("Negatron Slam"),
("Netherworld Grasp"),
("Netherworld Tentacles"),
("Neurotoxic Breath"),
("Neutrino Bolt"),
("Neutron Bomb"),
("Night Fall"),
("Nimble Slash"),
("Ninja Reflexes"),
("Nova"),
("Noxious Gas"),
("Nullify Pain"),
("O2 Boost"),
("Obscure Sustenance"),
("Obsidian Shield"),
("Offensive Adaptation"),
("Oil Slick Arrow"),
("Omega Maneuver"),
("One Thousand Cuts"),
("One with the Shield"),
("Oni"),
("Oppressive Gloom"),
("Orbiting Death"),
("Overcharge"),
("Overgrowth"),
("Overload"),
("Painbringer"),
("Paralizing Dart"),
("Paralytic Poison"),
("Paralyzing Blast"),
("Paralyzing Jolt"),
("Parasitic Aura"),
("Parasitic Leech"),
("Parry"),
("Particle Acceleration"),
("Particle Shielding"),
("Pendulum"),
("Penetrating Ray"),
("Penumbral Grasp"),
("Penumbral Shield"),
("Perfect Shot"),
("Permafrost"),
("Personal Force Field"),
("Petrifying Gaze"),
("Phalanx Fighting"),
("Phantasm"),
("Phantom Army"),
("Photon Grenade"),
("Photon Seekers"),
("Piercing Beam"),
("Piercing Rounds"),
("Pistols"),
("Placate"),
("Plasma Shield"),
("Poison Dart"),
("Poison Gas Arrow"),
("Poison Trap"),
("Poisonous Ray"),
("Positron Cell"),
("Positronic Fist"),
("Possess"),
("Power Armor"),
("Power Blast"),
("Power Bolt"),
("Power Boost"),
("Power Burst"),
("Power Drain"),
("Power of the Phoenix"),
("Power Push"),
("Power Shield"),
("Power Sink"),
("Power Siphon"),
("Power Slice"),
("Power Surge"),
("Power Thrust"),
("Practiced Brawler"),
("Precise Strike"),
("Propel"),
("Protector Bots"),
("Proton Armor"),
("Proton Scatter"),
("Proton Stream"),
("Proton Sweep"),
("Proton Therapy"),
("Proton Volley"),
("Psi Blade"),
("Psi Blade Sweep"),
("Psionic Dart"),
("Psionic Lance"),
("Psionic Strike"),
("Psionic Tornado"),
("Psychic Focus"),
("Psychic Scream"),
("Psychic Shockwave"),
("Psychic Wail"),
("Pulsar"),
("Pulse Rifle Blast"),
("Pulse Rifle Burst"),
("Pulverize"),
("Pummel"),
("Punch"),
("Quantum Acceleration"),
("Quantum Flight"),
("Quantum Shield"),
("Quasar"),
("Quick Recovery"),
("Quick Strike"),
("Quickness"),
("Quicksand"),
("Quills"),
("Radiant Aura"),
("Radiant Strike"),
("Radiation Infection"),
("Radiation Siphon"),
("Radiation Therapy"),
("Radioactive Cloud"),
("Radioactive Smash"),
("Rage"),
("Rain of Arrows"),
("Rain of Fire"),
("Ranged Shot"),
("Reach for the Limit"),
("Reaction Time"),
("Rebirth"),
("Rebuild DNA"),
("Reconstruction"),
("Recovery Aura"),
("Reform Essence"),
("Refractor Beam"),
("Regeneration Aura"),
("Regrowth"),
("Rehabilitating Circuit"),
("Reinforced"),
("Rend Armor"),
("Rending Flurry"),
("Repair"),
("Repel"),
("Repelling Force"),
("Repulsing Torrent"),
("Repulsion Bomb"),
("Repulsion Field"),
("Resilience"),
("Resist Elements"),
("Resist Energies"),
("Resist Physical Damage"),
("Restore Essence"),
("Resurgence"),
("Resurrect"),
("Revive"),
("Rib Cracker"),
("Ring of Fire"),
("Ripper"),
("Rise of the Phoenix"),
("Rise to the Challenge"),
("Rock Armor"),
("Rooted"),
("Roots"),
("Salt Crystals"),
("Savage Leap"),
("Savage Strike"),
("Scare"),
("School of Sharks"),
("Scorch"),
("Scramble Thoughts"),
("Scream"),
("Screech"),
("Second Wind"),
("Seeds of Confusion"),
("Seeker Drones"),
("Seishinteki Kyoyo"),
("Seismic Smash"),
("Serpent's Reach"),
("Serum"),
("Shadow Blast"),
("Shadow Bolt"),
("Shadow Cloak"),
("Shadow Dweller"),
("Shadow Fall"),
("Shadow Field"),
("Shadow Maul"),
("Shadow Punch"),
("Shadow Slip"),
("Shadowy Binds"),
("Share Pain"),
("Shatter"),
("Shield Charge"),
("Shin Breaker"),
("Shining Shield"),
("Shinobi"),
("Shinobi-Iri"),
("Shiver"),
("Shocking Grasp"),
("Shockwave"),
("Short Circuit"),
("Shout"),
("Shred"),
("Shriek"),
("Shuriken Throw"),
("Single Shot"),
("Singularity"),
("Siphon Life"),
("Siphon Power"),
("Siphon Speed"),
("Sirens Song"),
("Siren's Song"),
("Skewer"),
("Sky Splitter"),
("Slash"),
("Sleet"),
("Slice"),
("Slowed Response"),
("Slug"),
("Smashing Blow"),
("Smite"),
("Smoke"),
("Smoke Flash"),
("Smoke Grenade"),
("Snap Shot"),
("Sniper Blast"),
("Sniper Rifle"),
("Snow Storm"),
("Soaring Dragon"),
("Solar Flare"),
("Soldiers"),
("Sonic  Repulsion"),
("Sonic Barrier"),
("Sonic Cage"),
("Sonic Dispersion"),
("Sonic Haven"),
("Sonic Repulsion"),
("Sonic Siphon"),
("Soothe"),
("Soothing Aura"),
("Soul Absorption"),
("Soul Drain"),
("Soul Extraction"),
("Soul Storm"),
("Soul Tentacles"),
("Soul Transfer"),
("Spec Ops"),
("Spectral Terror"),
("Spectral Wounds"),
("Speed Boost"),
("Spin"),
("Spine Burst"),
("Spinning Kick"),
("Spinning Strike"),
("Spirit Shark Jaws"),
("Spirit Tree"),
("Spore Burst"),
("Spore Cloud"),
("Spot Prey"),
("Staff Mastery"),
("Stalagmites"),
("Starless Step"),
("Static Discharge"),
("Static Field"),
("Static Shield"),
("Steam Spray"),
("Steamy Mist"),
("Sting of the Wasp"),
("Stone Cages"),
("Stone Fist"),
("Stone Mallet"),
("Stone Prison"),
("Stone Skin"),
("Stone Spears"),
("Storm Kick"),
("Strangler"),
("Strength of Will"),
("Strike"),
("Stun"),
("Stunning Shot"),
("Stygian Circle"),
("Stygian Return"),
("Subdual"),
("Subdue"),
("Summon Adept"),
("Summon Coralax"),
("Summon Demon Prince"),
("Summon Demonlings"),
("Summon Demons"),
("Summon Dire Wolf"),
("Summon Lions"),
("Summon Mistress"),
("Summon Spiderlings"),
("Summon Tarantula"),
("Summon Wolves"),
("Sunless Mire"),
("Superior Invisibility"),
("Suppress Pain"),
("Suppression"),
("Suppressive Fire"),
("Surveillance"),
("Swap Ammo"),
("Sweeping Cross"),
("Sweeping Strike"),
("Swipe"),
("Swoop"),
("Synaptic Overload"),
("Tactical Training: Assault"),
("Tactical Training: Leadership"),
("Tactical Training: Maneuvers"),
("Tactical Training: Vengeance"),
("Tactical Upgrade"),
("Tame Beasts"),
("Tar Patch"),
("Targeting Drone"),
("Taser"),
("Tashibishi"),
("Taunt"),
("Telekinesis"),
("Telekinetic Blast"),
("Telekinetic Blow"),
("Telekinetic Thrust"),
("Temp Invulnerability"),
("Temperature Protection"),
("Temporal Healing"),
("Temporal Mending"),
("Temporal Selection"),
("Tenebrous Regeneration"),
("Tenebrous Tentacles"),
("Terrify"),
("Tesla Cage"),
("Thaw"),
("The Lotus Drops"),
("Thermal Shield"),
("Thorn Barrage"),
("Thorn Burst"),
("Thorntrops"),
("Thorny Darts"),
("Throw Sand"),
("Throw Spines"),
("Thunder Clap"),
("Thunder Kick"),
("Thunder Strike"),
("Thunderous Blast"),
("Tidal Forces"),
("Time Bomb"),
("Time Crawl"),
("Time Lord"),
("Time Shift"),
("Time Stop"),
("Time Wall"),
("Time's Juncture"),
("Titan Sweep"),
("Tornado"),
("Torrent"),
("Total Domination"),
("Total Focus"),
("Touch of Fear"),
("Touch of the Beyond"),
("Tough Hide"),
("Toxins"),
("Train Beasts"),
("Train Ninjas"),
("Transference"),
("Transfusion"),
("Tremor"),
("Triage Beacon"),
("Trick Shot"),
("Trip Mine"),
("True Grit"),
("Twilight Grasp"),
("Twilight Shield"),
("Typhoon's Edge"),
("Umbra Beast"),
("Umbral Torrent"),
("Unchain Essence"),
("Unkindness"),
("Unstoppable"),
("Unyeilding"),
("Unyielding"),
("Up to the Challenge"),
("Upgrade Equipment"),
("Upgrade Robot"),
("Upshot"),
("Vengeful Slice"),
("Venom Grenade"),
("Venomous Gas"),
("Vicious Slash"),
("Vines"),
("Volcanic Gasses"),
("Voltaic Sentinel"),
("Warmth"),
("Warriors Challenge"),
("Warrior's Provocation"),
("Water Burst"),
("Water Jet"),
("Weaken"),
("Web Cocoon"),
("Web Envelope"),
("Web Grenade"),
("Wet Ice"),
("Whirling Axe"),
("Whirling Hands"),
("Whirling Mace"),
("Whirling Smash"),
("Whirling Sword"),
("Whirlpool"),
("White Dwarf"),
("Wide Area Web Grenade"),
("Wild Bastion"),
("Wild Fortress"),
("Wild Growth"),
("Will Domination"),
("Wolf Spider Armor"),
("World of Confusion"),
("World of Pain"),
("Wormhole"),
("X-Ray Beam"),
("Zapp"),
("Zapping Bolt"),
("Zombie Horde");
